" This line starts pathogen; uncomment if not installed
execute pathogen#infect()

" Pathogen packages:
"   rainbow_parentheses.vim
"   rust.vim 
"   julia-vim
"   vim-clojure-static
"   vim-colors-solarized
"   vim-fireplace

syntax enable
set background=dark

" Next two lines are for iTerm2 only; remove them elsewhere
let g:solarized_visibility = "high"
let g:solarized_visibility = "high"

" Comment this out if solarized is not installed
colorscheme solarized

set ignorecase
set smartcase
set number

set expandtab
set tabstop=4
set softtabstop=4
set autoindent

" Found this script somewhere; ideal settings for word processing
func! WordProcessorMode()
	setlocal formatoptions=1
	setlocal noexpandtab
	map j gj
	map k gk
	set complete+=s
	set formatprg=par
	setlocal wrap
	setlocal linebreak
endfu

com! WP call WordProcessorMode()
command RP RainbowParenthesesToggle
