" This line starts pathogen; uncomment if not installed
execute pathogen#infect()

syntax enable
set background=dark

" Next two lines are for iTerm2 only; remove them elsewhere
let g:solarized_visibility = "high"
let g:solarized_visibility = "high"

" Comment this out if solarized is not installed
colorscheme solarized

set ignorecase
set smartcase
set number

set tabstop=4
set autoindent

" Found this script somewhere; ideal settings for word processing
func! WordProcessorMode()
	setlocal formatoptions=1
	setlocal noexpandtab
	map j gj
	map k gk
	set complete+=s
	set formatprg=par
	setlocal wrap
	setlocal linebreak
endfu

com! WP call WordProcessorMode()
