alias tmux="TERM=screen-256color-bce tmux"
alias ls="ls -F"
alias sl="ls -F"
alias l="ls -F"
alias la="ls -AF"
alias ll="ls -al"
alias c="clear; ls -F"
alias cl="clear"
alias s="sudo"
alias sf="screenfetch"

# nixos doesn't have /bin/bash
alias stack="stack --nix"

# os-x only
#alias python="python3"
#alias pip="pip3"

# auto-open tmux if it's not open already
#if [ "$TMUX" = "" ]; then tmux; fi

# prompt with 
autoload -U colors && colors
PROMPT="%{$fg[blue]%}λ %{$reset_color%}"
RPROMPT="%{$fg[white]%}%~%{$reset_color%}"

# line-editing with vi bindings
set -o vi

# bash history is nice
bindkey "^R" history-incremental-search-backward

# better tab-completion; case-insensitive
autoload -U compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# PATH
#export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin
export PATH=$PATH:/home/carter/bin
